"""Initial migration from SQL schema

Revision ID: 5c65d94e5393
Revises: eb2eb3a2a127
Create Date: 2024-12-09 17:58:32.439009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c65d94e5393'
down_revision: Union[str, None] = 'eb2eb3a2a127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sala',
    sa.Column('id_Sala', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_Sala')
    )
    op.add_column('Asistent_Examen', sa.Column('id_Profesor_1', sa.Integer(), nullable=False))
    op.drop_constraint('FK__Asistent___id_Pr__29AC2CE0', 'Asistent_Examen', type_='foreignkey')
    op.create_foreign_key(None, 'Asistent_Examen', 'Profesor', ['id_Profesor_1'], ['id_Profesor'])
    op.drop_column('Asistent_Examen', 'id_Profesor')
    op.add_column('Cerere', sa.Column('id_Student', sa.Integer(), nullable=False))
    op.add_column('Cerere', sa.Column('id_Grupa', sa.Integer(), nullable=False))
    op.alter_column('Cerere', 'status',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.create_foreign_key(None, 'Cerere', 'Grupa', ['id_Grupa'], ['id_Grupa'])
    op.create_foreign_key(None, 'Cerere', 'Student', ['id_Student'], ['id_Student'])
    op.add_column('Examen', sa.Column('id_Facultate', sa.Integer(), nullable=False))
    op.add_column('Examen', sa.Column('id_Profesor_1', sa.Integer(), nullable=False))
    op.add_column('Examen', sa.Column('id_Materie', sa.Integer(), nullable=False))
    op.add_column('Examen', sa.Column('id_Grupa', sa.Integer(), nullable=False))
    op.add_column('Examen', sa.Column('data', sa.Date(), nullable=False))
    op.add_column('Examen', sa.Column('id_Sala', sa.Integer(), nullable=False))
    op.alter_column('Examen', 'id_Cerere',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('FK__Examen__id_Cerer__24E777C3', 'Examen', type_='foreignkey')
    op.create_foreign_key(None, 'Examen', 'Grupa', ['id_Grupa'], ['id_Grupa'])
    op.create_foreign_key(None, 'Examen', 'Sala', ['id_Sala'], ['id_Sala'])
    op.create_foreign_key(None, 'Examen', 'Facultate', ['id_Facultate'], ['id_Facultate'])
    op.create_foreign_key(None, 'Examen', 'Profesor', ['id_Profesor_1'], ['id_Profesor'])
    op.create_foreign_key(None, 'Examen', 'Cerere', ['id_Cerere'], ['id_Cerere'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Examen', 'Materie', ['id_Materie'], ['id_Materie'])
    op.drop_column('Examen', 'sala')
    op.add_column('Grupa', sa.Column('id_Facultate', sa.Integer(), nullable=False))
    op.drop_constraint('FK__Grupa__facultate__0C1BC9F9', 'Grupa', type_='foreignkey')
    op.create_foreign_key(None, 'Grupa', 'Facultate', ['id_Facultate'], ['id_Facultate'])
    op.drop_column('Grupa', 'facultate_id')
    op.add_column('Student', sa.Column('id_Grupa', sa.Integer(), nullable=False))
    op.drop_constraint('FK__Student__grupa_i__1B5E0D89', 'Student', type_='foreignkey')
    op.create_foreign_key(None, 'Student', 'Grupa', ['id_Grupa'], ['id_Grupa'])
    op.drop_column('Student', 'grupa_id')
    op.alter_column('User', 'parola',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=450),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'parola',
               existing_type=sa.VARCHAR(length=450),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.add_column('Student', sa.Column('grupa_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Student', type_='foreignkey')
    op.create_foreign_key('FK__Student__grupa_i__1B5E0D89', 'Student', 'Grupa', ['grupa_id'], ['id_Grupa'])
    op.drop_column('Student', 'id_Grupa')
    op.add_column('Grupa', sa.Column('facultate_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Grupa', type_='foreignkey')
    op.create_foreign_key('FK__Grupa__facultate__0C1BC9F9', 'Grupa', 'Facultate', ['facultate_id'], ['id_Facultate'])
    op.drop_column('Grupa', 'id_Facultate')
    op.add_column('Examen', sa.Column('sala', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Examen', type_='foreignkey')
    op.drop_constraint(None, 'Examen', type_='foreignkey')
    op.drop_constraint(None, 'Examen', type_='foreignkey')
    op.drop_constraint(None, 'Examen', type_='foreignkey')
    op.drop_constraint(None, 'Examen', type_='foreignkey')
    op.drop_constraint(None, 'Examen', type_='foreignkey')
    op.create_foreign_key('FK__Examen__id_Cerer__24E777C3', 'Examen', 'Cerere', ['id_Cerere'], ['id_Cerere'])
    op.alter_column('Examen', 'id_Cerere',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Examen', 'id_Sala')
    op.drop_column('Examen', 'data')
    op.drop_column('Examen', 'id_Grupa')
    op.drop_column('Examen', 'id_Materie')
    op.drop_column('Examen', 'id_Profesor_1')
    op.drop_column('Examen', 'id_Facultate')
    op.drop_constraint(None, 'Cerere', type_='foreignkey')
    op.drop_constraint(None, 'Cerere', type_='foreignkey')
    op.alter_column('Cerere', 'status',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('Cerere', 'id_Grupa')
    op.drop_column('Cerere', 'id_Student')
    op.add_column('Asistent_Examen', sa.Column('id_Profesor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Asistent_Examen', type_='foreignkey')
    op.create_foreign_key('FK__Asistent___id_Pr__29AC2CE0', 'Asistent_Examen', 'Profesor', ['id_Profesor'], ['id_Profesor'])
    op.drop_column('Asistent_Examen', 'id_Profesor_1')
    op.drop_table('Sala')
    # ### end Alembic commands ###
